class GMM:
    def __init__(self,n_components,covariance_type,tol,max_iter,reg_covar):
        ...
    def _init_params(self,X):
        """ Initialize means , Covariances , weights"""
        ...
    def _multivariate_gaussian(self,X,mean,cov):
        ...
    def _e_step(self,X):
        ...
    def _m_step(self,X,responsibilities):
        ...
    def _compute_covariance(self,X,responsibilities,mean):
        ...
    def _compute_log_likelihood(self, X):
        ...
    def fit(self,X):
        ...
    def predict(self,X):
        ...